language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
  - server/node_modules
install:
- npm install
- npm run server:install
before_script:
- npm run build
script:
- npm run unit
- npm run coverage
after_success:
- git add .
- git commit -m "发布"
- git push --force --quiet "https://${GITHUB_TOKEN}@github.com/WeiRu1016/myblog.git"
  master:master
- ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $server
- ssh $name@$server "./deploy.sh"
before_install:
- touch ~/.ssh/id_rsa
- openssl aes-256-cbc -K $encrypted_3286054f5a8a_key -iv $encrypted_3286054f5a8a_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: $server
