language: node_js
node_js:
 - "6"
services:
  - mongodb
cache:
    directories:
     - node_modules
     - server/node_modules
install:
  - npm install
  - npm run server:install
before_script:
  - npm run build
  - sleep 15
  - mongo baomax_blog --eval 'db.user.insert({username:"baomax",password:"baomax"});'
script: 
  # - npm run server
  - npm run unit
  - npm run coverage
# deploy:
#   skip_cleanup: true
#   provider: push
#   github-token: $GITHUB_TOKEN
#   keep-history: true
#   on:
#     branch: master
after_success:
  - git add .
  - git commit -m "发布"
  - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/WeiRu1016/myblog.git" master:master
  - ssh $name@$server "./deploy.sh"
