language: node_js
node_js:
 - "6"
services:
  - mongodb
cache:
    directories:
     - node_modules
install:
  - npm install
before_script:
  - npm run build
  - sleep 15
  - mongo baomax_blog --eval 'db.createUser({username:"baomax",password:"baomax"});'
script: 
  - npm run server
  - npm run unit
  - npm run coverage
deploy:
  skip_cleanup: true
  provider: pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
