language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
  - server/node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_1cf1ef5de06c_key -iv $encrypted_1cf1ef5de06c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
install:
- npm install
- npm run server:install
script:
- npm run build
- npm run unit
- npm run coverage
after_success:
- chmod 600 ~/.ssh/id_rsa
- tar -jcf dist.tar.gz dist
- scp -o StrictHostKeyChecking=no LogLevel=quiet dist.tar.gz $name@$server:~/
- ssh $name@$server -o StrictHostKeyChecking=no LogLevel=quiet "rm -rf dist && tar
  -jxf dist.tar.gz && sh deploy.sh"
addons:
  ssh_known_hosts:
  - git.example.com
  - "$server"
