language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
  - server/node_modules
install:
- npm install
- npm run server:install
before_script:
- npm run build
script:
- npm run unit
- npm run coverage
after_success:
- chmod 600 ~/.ssh/id_rsa
- git add .
- git commit -m "发布"
- git push --force --quiet "https://${GITHUB_TOKEN}@github.com/WeiRu1016/myblog.git"
  master:master
- ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $server
- ssh $name@$server "./deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_1cf1ef5de06c_key -iv $encrypted_1cf1ef5de06c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
addons:
  ssh_known_hosts:
  - git.example.com
  - "$server"
